on: workflow_call

name: build

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    runs-on: ${{ matrix.os }}
    name: check on ${{ matrix.os }} (${{ matrix.r }}
    continue-on-error: ${{ matrix.os == 'macOS-latest' }}

    strategy:
      fail-fast: false
      matrix:
        include:
        - {os: macOS-latest, r: 'release'}
        - {os: windows-latest, r: 'release'}
        - {os: ubuntu-latest, r: 'devel', http-user-agent: 'release'}
        - {os: ubuntu-latest, r: 'release', covr: 'yes'}
        - {os: ubuntu-latest, r: 'oldrel'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      _R_CHECK_CRAN_INCOMING_REMOTE_: false

    steps:
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.r }}
        http-user-agent: ${{ matrix.http-user-agent }}
        use-public-rspm: true
    - uses: r-lib/actions/setup-pandoc@v2
    - uses: r-lib/actions/setup-tinytex@v2

    - name: Install macOS dependencies
      if: ${{ runner.os == 'macOS' }}
      run: |
        brew install automake udunits
        echo "UDUNITS2_INCLUDE=/opt/homebrew/Cellar/udunits/2.2.28/include" >> $GITHUB_ENV
        echo "UDUNITS2_LIBS=/opt/homebrew/Cellar/udunits/2.2.28/lib" >> $GITHUB_ENV

    - name: Install Windows dependencies
      if: ${{ runner.os == 'Windows' }}
      run: pacman -Syu --noconfirm mingw-w64-ucrt-x86_64-udunits

    - name: Add units and errors as Remotes
      if: ${{ github.repository == 'r-quantities/quantities' }}
      run: |
        echo "Remotes: r-quantities/units, r-quantities/errors" >> DESCRIPTION

    - name: Install package dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::rcmdcheck, any::covr
        needs: check, coverage

    - name: Check
      uses: r-lib/actions/check-r-package@v2
      with:
        upload-snapshots: true

    - name: Test coverage
      if: ${{ success() && matrix.covr == 'yes' }}
      run: covr::codecov()
      shell: Rscript {0}
